/* eslint-disable max-lines */
export type CurrenciesApiResponse = {
    date: string
    usd: Usd
  }

  export type Usd = {
    "00": number
    "1inch": number
    aave: number
    abt: number
    ach: number
    acs: number
    ada: number
    aed: number
    aergo: number
    afn: number
    agld: number
    aioz: number
    akt: number
    alcx: number
    aleph: number
    algo: number
    alice: number
    all: number
    amd: number
    amp: number
    ang: number
    ankr: number
    ant: number
    aoa: number
    ape: number
    api3: number
    apt: number
    ar: number
    arb: number
    arpa: number
    ars: number
    asm: number
    ast: number
    ata: number
    atom: number
    ats: number
    auction: number
    aud: number
    audio: number
    aurora: number
    avax: number
    avt: number
    awg: number
    axl: number
    axs: number
    azm: number
    azn: number
    badger: number
    bake: number
    bal: number
    bam: number
    band: number
    bat: number
    bbd: number
    bch: number
    bdt: number
    bef: number
    bgn: number
    bhd: number
    bico: number
    bif: number
    bit: number
    blur: number
    blz: number
    bmd: number
    bnb: number
    bnd: number
    bnt: number
    bob: number
    boba: number
    bond: number
    brl: number
    bsd: number
    bsv: number
    bsw: number
    btc: number
    btcb: number
    btg: number
    btn: number
    btrst: number
    btt: number
    busd: number
    bwp: number
    byn: number
    byr: number
    bzd: number
    c98: number
    cad: number
    cake: number
    cbeth: number
    cdf: number
    celo: number
    celr: number
    cfx: number
    cgld: number
    chf: number
    chz: number
    clp: number
    clv: number
    cnh: number
    cny: number
    comp: number
    cop: number
    coti: number
    coval: number
    crc: number
    cro: number
    crpt: number
    crv: number
    cspr: number
    ctsi: number
    ctx: number
    cuc: number
    cup: number
    cvc: number
    cve: number
    cvx: number
    cyp: number
    czk: number
    dai: number
    dar: number
    dash: number
    dcr: number
    ddx: number
    dem: number
    deso: number
    dext: number
    dfi: number
    dia: number
    dimo: number
    djf: number
    dkk: number
    dnt: number
    doge: number
    dop: number
    dot: number
    drep: number
    dydx: number
    dyp: number
    dzd: number
    eek: number
    egld: number
    egp: number
    ela: number
    enj: number
    ens: number
    eos: number
    ern: number
    esp: number
    etb: number
    etc: number
    eth: number
    eth2: number
    eur: number
    euroc: number
    farm: number
    fei: number
    fet: number
    fida: number
    fil: number
    fim: number
    fis: number
    fjd: number
    fkp: number
    flow: number
    flr: number
    fort: number
    forth: number
    fox: number
    frax: number
    frf: number
    ftm: number
    ftt: number
    fx: number
    fxs: number
    gal: number
    gala: number
    gbp: number
    gel: number
    gfi: number
    ggp: number
    ghc: number
    ghs: number
    ghst: number
    gip: number
    glm: number
    gmd: number
    gmt: number
    gmx: number
    gnf: number
    gno: number
    gnt: number
    gods: number
    grd: number
    grt: number
    gst: number
    gt: number
    gtc: number
    gtq: number
    gusd: number
    gyd: number
    gyen: number
    hbar: number
    hft: number
    high: number
    hkd: number
    hnl: number
    hnt: number
    hopr: number
    hot: number
    hrk: number
    ht: number
    htg: number
    huf: number
    icp: number
    idex: number
    idr: number
    iep: number
    ils: number
    ilv: number
    imp: number
    imx: number
    index: number
    inj: number
    inr: number
    inv: number
    iotx: number
    iqd: number
    irr: number
    isk: number
    itl: number
    jasmy: number
    jep: number
    jmd: number
    jod: number
    jpy: number
    jup: number
    kas: number
    kava: number
    kcs: number
    kda: number
    keep: number
    kes: number
    kgs: number
    khr: number
    klay: number
    kmf: number
    knc: number
    kpw: number
    krl: number
    krw: number
    ksm: number
    kwd: number
    kyd: number
    kzt: number
    lak: number
    lbp: number
    lcx: number
    ldo: number
    leo: number
    link: number
    lit: number
    lkr: number
    loka: number
    loom: number
    lpt: number
    lqty: number
    lrc: number
    lrd: number
    lseth: number
    lsl: number
    ltc: number
    ltl: number
    luf: number
    luna: number
    lunc: number
    lvl: number
    lyd: number
    mad: number
    magic: number
    mana: number
    mask: number
    math: number
    matic: number
    mco2: number
    mdl: number
    mdt: number
    media: number
    metis: number
    mga: number
    mgf: number
    mina: number
    miota: number
    mir: number
    mkd: number
    mkr: number
    mln: number
    mmk: number
    mnde: number
    mnt: number
    mona: number
    mop: number
    mpl: number
    mro: number
    mru: number
    msol: number
    mtl: number
    multi: number
    mur: number
    musd: number
    muse: number
    mvr: number
    mwk: number
    mxc: number
    mxn: number
    mxv: number
    myr: number
    mzm: number
    mzn: number
    nad: number
    nct: number
    near: number
    neo: number
    nest: number
    nexo: number
    nft: number
    ngn: number
    nio: number
    nkn: number
    nlg: number
    nmr: number
    nok: number
    npr: number
    nu: number
    nzd: number
    ocean: number
    ogn: number
    okb: number
    omg: number
    omr: number
    one: number
    ooki: number
    op: number
    orca: number
    orn: number
    osmo: number
    oxt: number
    pab: number
    pax: number
    paxg: number
    pen: number
    pepe: number
    perp: number
    pgk: number
    php: number
    pkr: number
    pla: number
    pln: number
    plu: number
    png: number
    pols: number
    poly: number
    pond: number
    powr: number
    prime: number
    pro: number
    prq: number
    pte: number
    pundix: number
    pyg: number
    pyr: number
    pyusd: number
    qar: number
    qi: number
    qnt: number
    qsp: number
    qtum: number
    quick: number
    rad: number
    rai: number
    rare: number
    rari: number
    rbn: number
    ren: number
    rep: number
    repv2: number
    req: number
    rgt: number
    rlc: number
    rly: number
    rndr: number
    rol: number
    ron: number
    rose: number
    rpl: number
    rsd: number
    rub: number
    rune: number
    rvn: number
    rwf: number
    sand: number
    sar: number
    sbd: number
    scr: number
    sdd: number
    sdg: number
    sei: number
    sek: number
    sgd: number
    shib: number
    shp: number
    shping: number
    sit: number
    skk: number
    skl: number
    sle: number
    sll: number
    snt: number
    snx: number
    sol: number
    sos: number
    spa: number
    spell: number
    spl: number
    srd: number
    srg: number
    ssp: number
    std: number
    stg: number
    stn: number
    storj: number
    stx: number
    sui: number
    suku: number
    super: number
    sushi: number
    svc: number
    swftc: number
    sylo: number
    syn: number
    syp: number
    szl: number
    t: number
    thb: number
    theta: number
    time: number
    tjs: number
    tmm: number
    tmt: number
    tnd: number
    ton: number
    tone: number
    top: number
    trac: number
    trb: number
    tribe: number
    trl: number
    tru: number
    trx: number
    try: number
    ttd: number
    ttt: number
    tusd: number
    tvd: number
    tvk: number
    twd: number
    twt: number
    tzs: number
    uah: number
    ugx: number
    uma: number
    unfi: number
    uni: number
    upi: number
    usd: number
    usdc: number
    usdd: number
    usdp: number
    usdt: number
    ust: number
    uyu: number
    uzs: number
    val: number
    vara: number
    veb: number
    ved: number
    vef: number
    ves: number
    vet: number
    vgx: number
    vnd: number
    voxel: number
    vtho: number
    vuv: number
    wampl: number
    waves: number
    waxl: number
    wbtc: number
    wcfg: number
    wemix: number
    wluna: number
    woo: number
    wst: number
    xaf: number
    xag: number
    xau: number
    xaut: number
    xbt: number
    xcd: number
    xch: number
    xcn: number
    xdc: number
    xdr: number
    xec: number
    xem: number
    xlm: number
    xmon: number
    xmr: number
    xof: number
    xpd: number
    xpf: number
    xpt: number
    xrp: number
    xtz: number
    xyo: number
    yer: number
    yfi: number
    yfii: number
    zar: number
    zec: number
    zen: number
    zil: number
    zmk: number
    zmw: number
    zrx: number
    zwd: number
    zwl: number
}
