import type { GridTile } from 'src/app/types/grid-tile';

export const data: Array<GridTile> = [
  {
    text: 'My account',
    icon: 'account_circle',
    route: 'support/my-account',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Deposit and withdrawal',
    icon: 'payments',
    route: 'support/deposit-and-withdrawal',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Security',
    icon: 'lock',
    route: 'support/security',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Anonimity',
    icon: 'question_mark',
    route: 'support/anonimity',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'P2P',
    icon: 'group',
    route: 'support/p2p',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Policies',
    icon: 'policy',
    route: 'support/policies',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Transfer crypto',
    icon: 'sync_alt',
    route: 'support/transfer-crypto',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Contact',
    icon: 'call',
    route: 'support/contact',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Buy and sell',
    icon: 'currency_bitcoin',
    route: 'support/buy-and-sell',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Getting started',
    icon: 'map',
    route: 'support/getting-started',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Trading',
    icon: 'rocket',
    route: 'support/trading',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: 'Terms',
    icon: 'gavel',
    route: 'support/terms',
    isActive: true,
    cols: 1,
    rows: 1,
  },
];
