import type { GridTile } from 'src/app/types/grid-tile';

export const data: Array<GridTile> = [
  {
    text: $localize`My account` as string,
    icon: 'account_circle',
    route: 'support/my-account',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Deposit and withdrawal` as string,
    icon: 'payments',
    route: 'support/deposit-and-withdrawal',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Security` as string,
    icon: 'lock',
    route: 'support/security',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Anonimity` as string,
    icon: 'question_mark',
    route: 'support/anonimity',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`P2P` as string,
    icon: 'group',
    route: 'support/p2p',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Policies` as string,
    icon: 'policy',
    route: 'support/policies',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Transfer crypto` as string,
    icon: 'sync_alt',
    route: 'support/transfer-crypto',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Contact` as string,
    icon: 'call',
    route: 'support/contact',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Buy and sell` as string,
    icon: 'currency_bitcoin',
    route: 'support/buy-and-sell',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Getting started` as string,
    icon: 'map',
    route: 'support/getting-started',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Trading` as string,
    icon: 'rocket',
    route: 'support/trading',
    isActive: true,
    cols: 1,
    rows: 1,
  },
  {
    text: $localize`Terms` as string,
    icon: 'gavel',
    route: 'support/terms',
    isActive: true,
    cols: 1,
    rows: 1,
  },
];
