name: Validate commit

on:
  pull_request:
    # Running when the PR is assigned as Ready for review or when the PR is updated
    types:
      - ready_for_review
      - synchronize
      - opened
    branches: [main]

# Definindo as etapas da pipeline
jobs:
  lint:
    runs-on: ubuntu-latest
    name: linters
    container: node:16.20-alpine3.17
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run format
  # Etapa de build
  build:
    runs-on: ubuntu-latest
    name: build
    container: node:16.20-alpine3.17
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - run: npm ci
      - run: npm run build
  # Etapa de teste
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  # Definição das políticas de teste de cobertura
